/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import animation.AnimationJFrame;
import animation.AnimationSwing;
import java.awt.Color;
import java.awt.GridBagLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Peanut
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainPage() {
        //Setting JFrame
        this.setUndecorated(true); //for fadeIn and fadeOut, write before initComponents();
        initComponents();

        this.setLocationRelativeTo(null); //make JFrame middle of screan
        AnimationJFrame animationJFrame = new AnimationJFrame(this, 1000);
        //animationJFrame.setBackgroundTransparent(this);
        animationJFrame.fadeIn(1, 0);
        animationJFrame.moveFromUp(100, 1, 0);

        moveForm();
        moveTo();


        myjPanel.setLayout(new GridBagLayout());
        JPanel a = new JPanel();
        myjPanel.add(a);
        AnimationSwing animation2 = new AnimationSwing(a,1000);
        animation2.fadingIn(1, 0);
        animation2.moveFromUp(100, 1, 0);

        /// Animation for jButton 
        AnimationSwing animation1 = new AnimationSwing(jButton1,1000);
        jButton1.setBackground(Color.RED);
        jButton1.setContentAreaFilled(false); /////JButton mast be add (fadingIn /fadingOut)
        jButton1.setOpaque(true); /////JButton mast be add (fadingIn /fadingOut)
        animation1.fadingOut(1, 0);
        try {Thread.sleep(1000);} catch (InterruptedException ex) {}
        jButton1.disable();
    }

    private void moveTo() {
        AnimationSwing aniToDown = new AnimationSwing(toDown, 3000);
        aniToDown.moveToDown(50,  1, 0);
        aniToDown.fadingIn( 1, 0);

        AnimationSwing aniToLeft = new AnimationSwing(toLeft, 3000);
        aniToLeft.moveToLeft(50,  1, 0);
        aniToLeft.fadingIn( 1, 0);

        AnimationSwing aniToRight = new AnimationSwing(toRight, 3000);
        aniToRight.moveToRight(50,  1, 0);
        aniToRight.fadingIn( 1, 0);

        AnimationSwing aniToUp = new AnimationSwing(toUp, 3000);
        aniToUp.moveToUp(50,  1, 0);
        aniToUp.fadingIn( 1, 0);

        AnimationSwing aniToDownRight = new AnimationSwing(toDownRight, 3000);
        aniToDownRight.moveToDown(50,  1, 0);
        aniToDownRight.moveToRight(50,  1, 0);
        aniToDownRight.fadingIn( 1, 0);

        AnimationSwing anitoDownLeft = new AnimationSwing(toDownLeft, 3000);
        anitoDownLeft.moveToDown(50,  1, 0);
        anitoDownLeft.moveToLeft(50,  1, 0);
        anitoDownLeft.fadingIn( 1, 0);

        AnimationSwing aniToUpLeft = new AnimationSwing(toUpLeft, 3000);
        aniToUpLeft.moveToUp(50,  1, 0);
        aniToUpLeft.moveToLeft(50,  1, 0);
        aniToUpLeft.fadingIn( 1, 0);

        AnimationSwing aniToUpRight = new AnimationSwing(toUpRight, 3000);
        aniToUpRight.moveToUp(50,  1, 0);
        aniToUpRight.moveToRight(50,  1, 0);
        aniToUpRight.fadingIn( 1, 0);

    }

    private void moveForm() {
        AnimationSwing aniFromDown = new AnimationSwing(formDown, 3000);
        aniFromDown.moveFromDown(50,  1, 0);
        aniFromDown.fadingIn( 1, 0);

        AnimationSwing aniFromLeft = new AnimationSwing(formLeft, 3000);
        aniFromLeft.moveFromLeft(50,  1, 0);
        aniFromLeft.fadingIn( 1, 0);

        AnimationSwing aniFromRight = new AnimationSwing(formRight, 3000);
        aniFromRight.moveFromRight(50,  1, 0);
        aniFromRight.fadingIn( 1, 0);

        AnimationSwing aniFromUp = new AnimationSwing(formUp, 3000);
        aniFromUp.moveFromUp(50,  1, 0);
        aniFromUp.fadingIn( 1, 0);

        AnimationSwing aniFromDownRight = new AnimationSwing(formDownRight, 3000);
        aniFromDownRight.moveFromDown(50,  1, 0);
        aniFromDownRight.moveFromRight(50,  1, 0);
        aniFromDownRight.fadingIn( 1, 0);

        AnimationSwing aniFromDownLeft = new AnimationSwing(formDownLeft, 3000);
        aniFromDownLeft.moveFromDown(50,  1, 0);
        aniFromDownLeft.moveFromLeft(50,  1, 0);
        aniFromDownLeft.fadingIn( 1, 0);

        AnimationSwing aniFromUpLeft = new AnimationSwing(formUpLeft, 3000);
        aniFromUpLeft.moveFromUp(50,  1, 0);
        aniFromUpLeft.moveFromLeft(50,  1, 0);
        aniFromUpLeft.fadingIn(1, 0);

        AnimationSwing aniFromUpRight = new AnimationSwing(formUpRight, 3000);
        aniFromUpRight.moveFromUp(50,  1, 0);
        aniFromUpRight.moveFromRight(50,  1, 0);
        aniFromUpRight.fadingIn(1, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        myjPanel = new javax.swing.JPanel();
        toLeft = new javax.swing.JLabel();
        toUp = new javax.swing.JLabel();
        toRight = new javax.swing.JLabel();
        toDown = new javax.swing.JLabel();
        toUpLeft = new javax.swing.JLabel();
        toUpRight = new javax.swing.JLabel();
        toDownLeft = new javax.swing.JLabel();
        toDownRight = new javax.swing.JLabel();
        formDownLeft = new javax.swing.JLabel();
        formDownRight = new javax.swing.JLabel();
        formLeft = new javax.swing.JLabel();
        formUp = new javax.swing.JLabel();
        formRight = new javax.swing.JLabel();
        formDown = new javax.swing.JLabel();
        formUpLeft = new javax.swing.JLabel();
        formUpRight = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        myjPanel.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout myjPanelLayout = new javax.swing.GroupLayout(myjPanel);
        myjPanel.setLayout(myjPanelLayout);
        myjPanelLayout.setHorizontalGroup(
            myjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        myjPanelLayout.setVerticalGroup(
            myjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        toLeft.setText("Left");

        toUp.setText("Up");

        toRight.setText("Right");

        toDown.setText("Down");

        toUpLeft.setText("UpLeft");
        toUpLeft.setName(""); // NOI18N

        toUpRight.setText("UpRight");

        toDownLeft.setText("DownLeft");

        toDownRight.setText("DownRight");

        formDownLeft.setText("DownLeft");

        formDownRight.setText("DownRight");

        formLeft.setText("Left");

        formUp.setText("Up");

        formRight.setText("Right");

        formDown.setText("Down");

        formUpLeft.setText("UpLeft");

        formUpRight.setText("UpRight");

        btnExit.setBackground(new java.awt.Color(255, 0, 51));
        btnExit.setForeground(new java.awt.Color(255, 0, 51));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Exit");

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formUpLeft)
                        .addGap(107, 107, 107)
                        .addComponent(formUp))
                    .addComponent(formLeft)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formDownLeft)
                        .addGap(96, 96, 96)
                        .addComponent(formDown)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formRight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toUpLeft)
                                    .addComponent(toDownLeft))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toUp)
                                    .addComponent(toDown))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toDownRight)
                                    .addComponent(toRight)
                                    .addComponent(toUpRight))))
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formDownRight)
                            .addComponent(formUpRight))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(myjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toUpLeft)
                            .addComponent(toUp)
                            .addComponent(toUpRight))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toLeft)
                            .addComponent(toRight))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toDownLeft)
                            .addComponent(toDown)
                            .addComponent(toDownRight)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formUpLeft)
                            .addComponent(formUp)
                            .addComponent(formUpRight))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formLeft)
                            .addComponent(formRight))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formDownLeft)
                            .addComponent(formDown)
                            .addComponent(formDownRight))))
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
         int confirm = JOptionPane.showOptionDialog(this,
                        "Are You Sure to Close this Application?",
                        "Exit Confirmation", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (confirm == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnExit;
    private javax.swing.JLabel formDown;
    private javax.swing.JLabel formDownLeft;
    private javax.swing.JLabel formDownRight;
    private javax.swing.JLabel formLeft;
    private javax.swing.JLabel formRight;
    private javax.swing.JLabel formUp;
    private javax.swing.JLabel formUpLeft;
    private javax.swing.JLabel formUpRight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel myjPanel;
    private javax.swing.JLabel toDown;
    private javax.swing.JLabel toDownLeft;
    private javax.swing.JLabel toDownRight;
    private javax.swing.JLabel toLeft;
    private javax.swing.JLabel toRight;
    private javax.swing.JLabel toUp;
    private javax.swing.JLabel toUpLeft;
    private javax.swing.JLabel toUpRight;
    // End of variables declaration//GEN-END:variables
}
